services:
  db:
    image: postgres:latest
    container_name: logbook_db
    env_file:
      - .env
    ports:
      - 5439:5432
    volumes:
      - logbook_db_data:/var/lib/postgresql
    restart: on-failure

volumes:
  logbook_db_data: